spring.application.name=athletex-backend

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/athletex_db}

# Mail Configuration (Gmail SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:nooreply.athletex@gmail.com}
spring.mail.password=${MAIL_PASSWORD:doummbrbxxosmyla}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=false