package com.athletex.backend.service;

import com.athletex.backend.model.Achievement;
import com.athletex.backend.repository.AchievementRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class AchievementService {

    private final AchievementRepository achievementRepository;
    private final ActivityService activityService;

    /*
     * GET ALL ACHIEVEMENTS
     */
    public List<Achievement> getAchievements(String userId) {

        return achievementRepository
                .findByUserIdOrderByDateDesc(userId);
    }


    /*
     * GET ACHIEVEMENT COUNT
     */
    public long getAchievementCount(String userId) {

        return achievementRepository
                .countByUserId(userId);
    }


    /*
     * CREATE ACHIEVEMENT
     */
    public Achievement createAchievement(
            String userId,
            Achievement achievement
    ) {

        // ID should be generated by MongoDB
        achievement.setId(null);

        // Associate achievement with the logged-in athlete
        achievement.setUserId(userId);

        Achievement savedAchievement = achievementRepository.save(achievement);

        activityService.createActivity(
                userId,
                "achievement_added",
                "Achievement Unlocked",
                achievement.getTitle(),
                "🏅"
        );

        return savedAchievement;
    }
}